spring:
  datasource:
    URL: jdbc:postgresql://localhost:5432/pc_market
    username: postgres
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: aslziyomarket@gmail.com
    password: tpnf phql iopj ckqx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
server:
  port : 8080
